### ISSUE TITLE
ldconfig not found on Debian

### ISSUE THREAD

**Issue by cvuchener** [darealshinji/linuxdeploy-plugin-checkrt#12]
I am testing this to make a C++14 application run on Debian Jessie. Trying to run my AppImage displays `sh: 1: ldconfig: not found` error. The script then fails to load the bundled libstdc++.so and the application stops with a CXXABI error.

ldconfig is located in /sbin which is not in the path of regular users. With a PATH including /sbin, the AppImage starts correctly.

**Comment by darealshinji** [comment]
Can you test if it was fixed in https://github.com/darealshinji/AppImageKit-checkrt/commit/3b8e82101d9f7f892a4a4499afe67a6675a78809 ?

**Comment by cvuchener** [comment]
Thanks, it is fixed (at least on Debian Jessie).
