### ISSUE TITLE
Be less aggressive in substituting libraries

### ISSUE THREAD

**Issue by sgsaenger** [darealshinji/linuxdeploy-plugin-checkrt#14]
Per default, `AppRun.sh` compares the symbols of the system libstdc++ and the packaged one.
I'm not sure how portable and/or correct this is, especially with script-based applications, but isn't it enough to compare the symbols of the application?
e.g.
```
  sym_app=$(tr '\0' '\n' < "$exec" | grep -e '^GLIBCXX_3\.4' | sort -V | tail -n1)
```
This could partially solve e.g. mesa issues like https://github.com/sgsaenger/vipster/issues/30

**Comment by darealshinji** [comment]
Some of the bundled libraries might require a newer C++ library than the application, so that's not a solution either, in my opinion.
