### ISSUE TITLE
[bug] getcwd return worry path

### ISSUE THREAD

**Issue by lonsdale8734** [darealshinji/linuxdeploy-plugin-checkrt#15]
Using c/c++ on ubuntu, `getcwd` should return the path where AppImage is called. But the return is always FUSE mounted.

**Comment by darealshinji** [comment]
Is this issue related to my patch or the original (now deprecated) AppRun?
https://github.com/AppImage/AppImageKit/blob/deprecated/AppImageAssistant/AppRun.c

**Comment by lonsdale8734** [comment]
Building Appimage without the patch works correctly.

**Comment by darealshinji** [comment]
checkrt doesn't use the patched AppRun anymore.
