### ISSUE TITLE
fusermount: old style mounting not supported

### ISSUE THREAD

**Issue by vodka2** [darealshinji/linuxdeploy-plugin-checkrt#17]
When I build appimage with AppImageKit-checkrt for a FUSE application and then run it, I get an error:
```
fusermount: old style mounting not supported
```
Complete MWE: https://gist.github.com/vodka2/44e1a40c3bcfb2899b21bdcd555ba8eb
If comment the first 4 lines in `build.sh` or if I run the appimage as root, no error happens. I'm using Arch Linux.
What is wrong with this example?

**Comment by darealshinji** [comment]
Sorry for the late response. This seems to be related to AppImageKit or a general FUSE issue but not to the checkrt helper script/app.
