### ISSUE TITLE
Idea for Check AppImage

### ISSUE THREAD

**Issue by liberodark** [darealshinji/linuxdeploy-plugin-checkrt#19]
Hi,

On Yuzu actually Appimage build have been update but actually some issues is effective.
Update : https://github.com/yuzu-emu/yuzu/pull/6667

1. issue : https://github.com/yuzu-emu/yuzu/issues/8897
2. issue : https://github.com/yuzu-emu/yuzu/issues/8921

In two cases we probably want to use your script for check conformity of appimage.
What do you think about the idea to check for example : 

`./usr/bin/$exec "$*"`
vs
`exec ./usr/bin/yuzu "$@"`

Best Regards

**Comment by Docteh** [comment]
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

Right now
```
  exec="$(sed -n 's|^Exec=||p' *.desktop | head -1)"
```

could filter out `%f` like so
```
exec="$(sed -n -e 's|%f||' -e 's|^Exec=||p' *.desktop  | head -1)"
```

**Comment by darealshinji** [comment]
Looking up "special variables in Bash" I get the following information:
* `$*`: Gives you a string containing every command-line argument.
* `$@`: It stores the list of every command-line argument as an array.

Whether or not you start yuzu with the `exec` argument shouldn't make any difference.
I hope that helps. :)
