### ISSUE TITLE
[feature request] Remove the need for AppRun

### ISSUE THREAD

**Issue by probonopd** [darealshinji/linuxdeploy-plugin-checkrt#2]
Would it be possible to make a dummy library that gets loaded instead of libstdc++, then determines whether the system or bundled  libstdc++ should be loaded, and then would load that one in turn? This would greatly simplify using this, as it would remove the need for a custom AppRun, bash script or similar wrapper.

Background: In [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) we have moved away from AppRun binaries or scripts and just use a symlink to the main executable, as we think this is a much cleaner solution.

**Comment by darealshinji** [comment]
A dummy libstdc++ library? I wouldn't know how to do that without wrapping all the thousands C++ symbols.

**Comment by probonopd** [comment]
Argh yes, that's what I feared.
