### ISSUE TITLE
checkrt might segfault if a library contains both dynstr and strtab sections

### ISSUE THREAD

**Issue by al95** [darealshinji/linuxdeploy-plugin-checkrt#21]
As discovered investigating issue #20 , there seems to be a bug in the way checkrt searches for the addresses of the `.strtab` and `.dynstr` sections.

Reading [lines 147-165](https://github.com/darealshinji/AppImageKit-checkrt/blob/3b0f28c71f630178f28881f1a82d6d038bb12cc7/src/checkrt.c#L147:L165), it seems that finding either the `.strtab` section or the `.dynstr` section stops the search loop with a `break` statement.
This means that if a library contains both `.strtab` and `.dynstr`, only one of the addresses will be set, while the other address will stay at the value set at [lines 143-144](https://github.com/darealshinji/AppImageKit-checkrt/blob/3b0f28c71f630178f28881f1a82d6d038bb12cc7/src/checkrt.c#L143:L144) .

I discovered this by accident by making checkrt check `libstdc++.so.6`  before `libgcc_s.so.1`, swapping [lines 374-378](https://github.com/darealshinji/AppImageKit-checkrt/blob/3b0f28c71f630178f28881f1a82d6d038bb12cc7/src/checkrt.c#L374:L378) with [lines 380-384](https://github.com/darealshinji/AppImageKit-checkrt/blob/3b0f28c71f630178f28881f1a82d6d038bb12cc7/src/checkrt.c#L380:L384) (and moving the `int var`).
Doing that makes checkrt segfault at the `strncmp` at [line 194](https://github.com/darealshinji/AppImageKit-checkrt/blob/3b0f28c71f630178f28881f1a82d6d038bb12cc7/src/checkrt.c#L194).

Deleting the two breaks at [line 157](https://github.com/darealshinji/AppImageKit-checkrt/blob/3b0f28c71f630178f28881f1a82d6d038bb12cc7/src/checkrt.c#L157) and [line 163](https://github.com/darealshinji/AppImageKit-checkrt/blob/3b0f28c71f630178f28881f1a82d6d038bb12cc7/src/checkrt.c#L163) fixes the segfault and checkrt runs successfully.

**Comment by darealshinji** [comment]
Thanks for this find. Does this also fix #20 ?

**Comment by al95** [comment]
> Thanks for this find. Does this also fix #20 ?

No, that's a glibc bug. I've reported it upstream: https://sourceware.org/bugzilla/show_bug.cgi?id=29600
