### ISSUE TITLE
Do not store generated plugin script in the repository

### ISSUE THREAD

**Issue by TheAssassin** [darealshinji/linuxdeploy-plugin-checkrt#22]
While this works reasonably well, it's an antipattern to include autogenerated bits in a repository.

You could use a tool like [pyuploadtool](https://github.com/TheAssassin/pyuploadtool) to create a continuous GitHub release with the generated file.

I can implement a basic workflow if you like the idea.

**Comment by darealshinji** [comment]
> I can implement a basic workflow if you like the idea.

Yes, that sounds good.

**Comment by darealshinji** [comment]
Can you help me to create a workflow? I can't seem to get it to work.

**Comment by TheAssassin** [comment]
I'll send a PR.
