### ISSUE TITLE
Built files should not be located inside `apprun-hooks` directory

### ISSUE THREAD

**Issue by TheAssassin** [darealshinji/linuxdeploy-plugin-checkrt#24]
I recently helped debug a problem that occurred with https://github.com/linuxdeploy/linuxdeploy-plugin-native_packages/. This output plugin deploys autogenerated helper scripts in `/usr/bin` for every desktop entry in the AppImage to imitate classic packaging.

There is no technical need for the files this plugin generates during build time to be located within that hooks directory. We should move the files outside of there, e.g., one level up.

Of course, the output plugin will receive some improvements to filter out seemingly incompatible files. But I'd also like to narrow the plugin specification to limit the directory to source-able shell scripts.

**Comment by TheAssassin** [comment]
Workaround implemented in https://github.com/linuxdeploy/linuxdeploy-plugin-native_packages/commit/67478609e7fb36452604f924f409cca34f93051b. I might send a PR eventually to relocate the files generated by this script.

**Comment by darealshinji** [comment]
What location would you suggest to put the other files in? Maybe `"$APPDIR/.linuxdeploy-plugin-checkrt` or `$APPDIR/usr/share/linuxdeploy-plugin-checkrt`?

**Comment by TheAssassin** [comment]
`$APPDIR/checkrt` or whatever else location you like. I don't really care, honestly. A hidden directory is not needed. Also, we don't need to hide it in `usr`. (To some extent, I'd say it's best practice and convention to put the application into usr/ and the packaging stuff outside of it.)

**Comment by darealshinji** [comment]
I've changed it to "$APPDIR/checkrt":  https://github.com/darealshinji/linuxdeploy-plugin-checkrt/commit/126fa22dd6fe4d457116a4d3616f665aba719d02

**Comment by TheAssassin** [comment]
Looks good, thanks! Have not tested it yet, but I'll open a new issue should the problems continue.
