### ISSUE TITLE
Regression: plugin not loaded as path in linuxdeploy-plugin-checkrt.sh are broken

### ISSUE THREAD

**Issue by TheOneRing** [darealshinji/linuxdeploy-plugin-checkrt#28]
Wrong paths in https://github.com/darealshinji/linuxdeploy-plugin-checkrt/commit/126fa22dd6fe4d457116a4d3616f665aba719d02 result in plugin not being loaded.

**Comment by darealshinji** [comment]
You're right. This should fix it: https://github.com/darealshinji/linuxdeploy-plugin-checkrt/commit/8d52bcc643491d01a4f603c74cb79331ac72398f
