### ISSUE TITLE
Optional libraries must not affect binaries loaded from outside the AppImage

### ISSUE THREAD

**Issue by probonopd** [darealshinji/linuxdeploy-plugin-checkrt#3]
Using `xubuntu-16.04.1-desktop-amd64.iso` and `Audacity-dc63bfe-x86_64.AppImage` from https://github.com/probonopd/audacity/releases, when I select Help -> "Check for updates", it fails:

> "Failed to execute default Web Browser.
> input/output error"

On the command line I get:

```
/usr/lib/firefox/firefox: relocation error: /usr/lib/firefox/firefox:
symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4copyEPcmm,
version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

I suspect this to be a side effect of using AppImageKit-checkrt.

This is a workaround:

```
./Audacity-dc63bfe-x86_64.AppImage --appimage-extract
rm squashfs-root/usr/optional/libstdc++/libstdc++.so.6
./squashfs-root/AppRun
```

**Comment by probonopd** [comment]
The current implementation may lead to issues if the payload application launches other applications that reside in the base system, that is, outside of the AppImage. KDevelop is an example of such an application. In these cases, the [appimage-exec-wrapper](https://cgit.kde.org/scratch/brauch/appimage-exec-wrapper.git/) library can be used together with the AppImage distribution mechanism. Place the library somewhere in your AppImage and point `LD_PRELOAD` to it before launching your application. Whenever your application invokes a child process through `execv()` or `execve()`, this wrapper will intercept the call and see if the child process lies outside of the bundled appdir. If it does, the wrapper will attempt to undo any changes done to environment variables before launching the process, since you probably did not intend to launch it with e.g. the `LD_LIBRARY_PATH` you previously set for your application. 

It would be nice if such a mechanism could be integrated directly into AppImageKit-checkrt.

**Comment by probonopd** [comment]
Ping @darealshinji - this is blocking https://github.com/probonopd/audacity/issues/6

**Comment by darealshinji** [comment]
There's an update. The appimage-exec-wrapper library (`usr/optional/exec.so`) will now be loaded if `usr/optional/libstdc++/libstdc++.so.6` and/or `usr/optional/libgcc_s/libgcc_s.so.1` are found.

**Comment by probonopd** [comment]
Thanks @darealshinji.
Can you please make `exec.so` available for download on GitHub Releases, too?

**Comment by darealshinji** [comment]
They're available for download.

**Comment by probonopd** [comment]
Thank you. Greatly appreciated. Let's see how https://github.com/probonopd/audacity/commit/1732ea4f3b4a99eb9cb1bc25fbad0e8a87bd3400 goes.

**Comment by probonopd** [comment]
Closing here since a lot has changed since I had reported this for the first time; however, the problem persists. Hence continuing here: https://github.com/darealshinji/AppImageKit-checkrt/issues/9
