### ISSUE TITLE
exec.soA from LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by probonopd** [darealshinji/linuxdeploy-plugin-checkrt#4]
On `xubuntu-16.04.1-desktop-amd64.iso` with https://github.com/probonopd/audacity/releases/download/checkrt/Audacity-63de7f0-x86_64.AppImage:

```
ERROR: ld.so: object '/tmp/.mount_AudaciivUspk/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudaciivUspk/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudaciivUspk/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudaciivUspk/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/.mount_AudaciivUspk/usr/optional/exec.soA' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

Where is the extra "A" coming from?

Interesting: If I run

```
./Audacity-63de7f0-x86_64.AppImage --appimage-extract
./squashfs-root/AppRun
```

then I do __not__ see these messages.

**Comment by darealshinji** [comment]
Weird indeed. This is the part where it's preloaded:
``` c
    if (bundle_cxx == 1 || bundle_gcc == 1) {
        optional_ld_preload = malloc(strlen("LD_PRELOAD=") + strlen(EXEC_SO) + 1 + len);
        sprintf(optional_ld_preload, "LD_PRELOAD=%s/" EXEC_SO, usr_in_appdir);
    }
```
I guess the allocated string is too long? Maybe I should remove the `+ 1` or `memset()` is to 0?

**Comment by probonopd** [comment]
I am a bit puzzled too. Could it be we need to terminate strings with `\0`? Just a wild guess.

**Comment by darealshinji** [comment]
Made an update on it. Can you check if it now works?

**Comment by probonopd** [comment]
Triggered a new build of https://github.com/probonopd/audacity/releases - let's see how it goes.

**Comment by probonopd** [comment]
Giving an instant segfault now -  https://github.com/probonopd/audacity/releases/download/continuous/Audacity-a796086-x86_64.AppImage

**Comment by darealshinji** [comment]
I will investigate this. The audacity binary file is not stripped by the way.

**Comment by probonopd** [comment]
Thanks @darealshinji

**Comment by darealshinji** [comment]
Indeed weird. There was an 'a' appended for me too when I built an AppImage with it. Now it's working when I rebuilt the AppImage with the new AppRun binary.

**Comment by probonopd** [comment]
So what is/was the solution?

**Comment by darealshinji** [comment]
Looks like I didn't allocate enough space. I usually prefer C++ to avoid stuff like this.

**Comment by probonopd** [comment]
I rebuilt the Audacity AppImage: https://github.com/probonopd/audacity/releases/download/continuous/Audacity-095ee91-x86_64.AppImage

Now it is no longer segfaulting, but it seems not to be loading libstdc++ either, as can be seen on an Ubuntu 14.04 system:

```
audacity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by audacity)
audacity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by audacity)
```

The AppImage contains (as can be inspected by running it with `--appimage-extract`):

```
usr/optional/libstdc++/libstdc++.so.6
usr/optional/exec.so
```

Please advise.

**Comment by probonopd** [comment]
Still getting this with the newest builds, e.g., Audacity_for_JACK-f3a0554-x86_64.AppImage from https://github.com/probonopd/audacity/releases.

**Comment by pamarcos** [comment]
I have tried https://github.com/probonopd/audacity/releases/download/continuous/Audacity-095ee91-x86_64.AppImage, but it works fine in my Ubuntu 14.04. I do have `GLIBCXX_3.4.24` in my libstdc++ though, so it should be using my system version.

I think we could introduce an env variable to help debugging checkrt logic. This way, instead of having the `printf`s commented out https://github.com/darealshinji/AppImageKit-checkrt/blob/master/exec.c#L284, https://github.com/darealshinji/AppImageKit-checkrt/blob/master/checkrt.c#L75-L76, https://github.com/darealshinji/AppImageKit-checkrt/blob/master/checkrt.c#L124 etc, we could have something like:

```
// checkrt.h
extern int debug_flag;

#define DEBUG(...) do { \
    if (debug_flag) \
        printf(__VA_ARGS__); \
} while (0)
```

```
// checkrt.c
int debug_flag = getenv("APPIMAGE_CHECKRT_DEBUG") ? 1 : 0;
```

What do you guys think? I will probably open another PR for that

**Comment by probonopd** [comment]
Good idea @pamarcos. Let's see:

```
# Extract AppImage

Downloads/Audacity_for_JACK-e06a6fd-x86_64.AppImage --appimage-extract

# Put in the latest files from this project, commit hash 2f04ad8

mv Downloads/AppRun-patched-x86_64 squashfs-root/AppRun
chmod +x squashfs-root/AppRun
mv Downloads/exec-x86_64.so squashfs-root/usr/optional/exec.so

# Try to run on Xubuntu 16.04

squashfs-root/AppRun 
/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ==> GLIBCXX_3.4.21 (21)
./optional/libstdc++/libstdc++.so.6 ==> GLIBCXX_3.4.24 (24)

optional: /home/me/squashfs-root/usr/optional/libstdc++:
optional_ld_preload: LD_PRELOAD=/home/me/squashfs-root/usr/optional/exec.so
audacity: symbol lookup error: /home/me/squashfs-root/usr/optional/exec.so: undefined symbol: debug_flag

# Now trying the same on Ubuntu 14.04

/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ==> GLIBCXX_3.4.19 (19)
./optional/libstdc++/libstdc++.so.6 ==> GLIBCXX_3.4.24 (24)

optional: /mnt/usr/optional/libstdc++:
optional_ld_preload: LD_PRELOAD=/mnt/usr/optional/exec.so
audacity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by audacity)
audacity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by audacity)
```

Am I missing something?

**Comment by pamarcos** [comment]
I have already fixed the `audacity: symbol lookup error: /home/me/squashfs-root/usr/optional/exec.so: undefined symbol: debug_flag
` error at https://github.com/darealshinji/AppImageKit-checkrt/pull/7. I don't know why LD doesn't complain about that when I use that `exec.so` with my own AppImage.

For what I see in your test, optional is set correctly to `[APPDIR]/usr/optional/libstdc++`, which is appended to the `PATH` env variable. Can you try setting `LD_LIBRARY_PATH=[APPDIR]/usr/optional/libstdc++` to see whether the internal libstdc++ is picked up?

**Comment by probonopd** [comment]
Yay @pamarcos when I do that then it works on both versions. Do you know how to fix this so that `LD_LIBRARY_PATH` is not needed to be set manually?

**Comment by pamarcos** [comment]
I created a PR that intends to fix that: https://github.com/darealshinji/AppImageKit-checkrt/pull/8

You can test it downloading from Travis CI (https://travis-ci.org/darealshinji/AppImageKit-checkrt/jobs/325909001) the binaries for that PR:

https://transfer.sh/OrlTV/AppRun-patched-x86_64
https://transfer.sh/5ndmJ/exec-x86_64.so

**Comment by probonopd** [comment]
Thanks @pamarcos - I have tested this on Ubuntu 14.04 and 16.04 and _it works_ 👍

**Comment by probonopd** [comment]
I no longer get the "cannot be preloaded" error.

**Comment by probonopd** [comment]
Thank you @darealshinji and @pamarcos - it looks like at least for my Audacity builds at https://github.com/probonopd/audacity/releases this appears to be working properly now since a while. Great!

**Comment by pamarcos** [comment]
Cool, glad to help on this. We're also using this and so far we've had no issues. Let's hope it continues like that. In any case, I'll help fixing whatever we see in the future.
